### ISSUE TITLE
phantom firework sound occasionally plays after exiting(?) network

### ISSUE THREAD

**Issue by HamaIndustries** [Lgmrszd/anshar#7]

**Comment by Lgmrszd** [comment]
ay ay captain

**Comment by Lgmrszd** [comment]
Pinpointed the problem:
- The delayed sound is actually the one playing on entering the network, not exiting it.
- On entering the network, there's a chance for S2C effect packet to take effect on client when the player is already teleported to the up high. When this happens, you don't hear the sound of the effect. Instead, it is delayed proportionally to the distance between the player and the firework explosion source.
- Since we're up high on Y=10000, the delay is very big.
- The sound delay is only calculated once, I guess it makes sense for vanilla as the firework explosion effect only occurs on client in normal conditions within player's render/load distance with delay not being that big, and the player doesn't usually get moved thousands of blocks in a blink.

**Comment by Lgmrszd** [comment]
I'd say it is fixed for now: now we don't send firework explosion effect to the player who enters the network.
This issue is still *might* happen when exiting, but I haven't noticed a single time of this happening.
